"""initial sentinel schema

Revision ID: 43eba7620db9
Revises: 
Create Date: 2026-06-01 18:53:13.227622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43eba7620db9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('approval_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_approval_id'), 'approvals', ['approval_id'], unique=True)
    op.create_index(op.f('ix_approvals_service'), 'approvals', ['service'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    op.create_table('deployments',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deployment_name', sa.String(length=255), nullable=False),
    sa.Column('namespace', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('replicas', sa.Integer(), nullable=False),
    sa.Column('available_replicas', sa.Integer(), nullable=True),
    sa.Column('updated_replicas', sa.Integer(), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_deployment_name'), 'deployments', ['deployment_name'], unique=False)
    op.create_index(op.f('ix_deployments_namespace'), 'deployments', ['namespace'], unique=False)
    op.create_index(op.f('ix_deployments_timestamp'), 'deployments', ['timestamp'], unique=False)
    op.create_table('escalations',
    sa.Column('escalation_id', sa.String(length=255), nullable=False),
    sa.Column('recovery_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('escalation_reason', sa.String(length=500), nullable=False),
    sa.Column('target', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escalations_escalation_id'), 'escalations', ['escalation_id'], unique=True)
    op.create_index(op.f('ix_escalations_recovery_id'), 'escalations', ['recovery_id'], unique=False)
    op.create_index(op.f('ix_escalations_tenant_id'), 'escalations', ['tenant_id'], unique=False)
    op.create_table('execution_audits',
    sa.Column('audit_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('approval_id', sa.String(length=255), nullable=True),
    sa.Column('execution_id', sa.String(length=255), nullable=True),
    sa.Column('verification_id', sa.String(length=255), nullable=True),
    sa.Column('recovery_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_audits_approval_id'), 'execution_audits', ['approval_id'], unique=False)
    op.create_index(op.f('ix_execution_audits_audit_id'), 'execution_audits', ['audit_id'], unique=True)
    op.create_index(op.f('ix_execution_audits_execution_id'), 'execution_audits', ['execution_id'], unique=False)
    op.create_index(op.f('ix_execution_audits_recovery_id'), 'execution_audits', ['recovery_id'], unique=False)
    op.create_index(op.f('ix_execution_audits_tenant_id'), 'execution_audits', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_execution_audits_verification_id'), 'execution_audits', ['verification_id'], unique=False)
    op.create_table('executions',
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('approval_id', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executions_approval_id'), 'executions', ['approval_id'], unique=False)
    op.create_index(op.f('ix_executions_execution_id'), 'executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_executions_tenant_id'), 'executions', ['tenant_id'], unique=False)
    op.create_table('executive_reports',
    sa.Column('report_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executive_reports_report_id'), 'executive_reports', ['report_id'], unique=True)
    op.create_index(op.f('ix_executive_reports_service'), 'executive_reports', ['service'], unique=False)
    op.create_index(op.f('ix_executive_reports_tenant_id'), 'executive_reports', ['tenant_id'], unique=False)
    op.create_table('incident_states',
    sa.Column('incident_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('current_state', sa.String(length=100), nullable=False),
    sa.Column('source_topic', sa.String(length=255), nullable=False),
    sa.Column('updated_at_event', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_states_current_state'), 'incident_states', ['current_state'], unique=False)
    op.create_index(op.f('ix_incident_states_incident_id'), 'incident_states', ['incident_id'], unique=True)
    op.create_index(op.f('ix_incident_states_service'), 'incident_states', ['service'], unique=False)
    op.create_index(op.f('ix_incident_states_tenant_id'), 'incident_states', ['tenant_id'], unique=False)
    op.create_table('incidents',
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('incident_priority', sa.String(length=20), nullable=False),
    sa.Column('impact_score', sa.Float(), nullable=False),
    sa.Column('final_risk_score', sa.Float(), nullable=False),
    sa.Column('requires_human_review', sa.Boolean(), nullable=False),
    sa.Column('escalation_required', sa.Boolean(), nullable=False),
    sa.Column('aggregated_event', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_incident_service_priority', 'incidents', ['service', 'incident_priority'], unique=False)
    op.create_index(op.f('ix_incidents_incident_priority'), 'incidents', ['incident_priority'], unique=False)
    op.create_index(op.f('ix_incidents_service'), 'incidents', ['service'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('investigations',
    sa.Column('investigation_id', sa.String(length=255), nullable=False),
    sa.Column('incident_id', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_incident_id'), 'investigations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_investigations_investigation_id'), 'investigations', ['investigation_id'], unique=True)
    op.create_index(op.f('ix_investigations_tenant_id'), 'investigations', ['tenant_id'], unique=False)
    op.create_table('knowledge_records',
    sa.Column('knowledge_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('pattern', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('remediation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_incident_type', sa.String(length=100), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('created_at_event', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_records_knowledge_id'), 'knowledge_records', ['knowledge_id'], unique=True)
    op.create_index(op.f('ix_knowledge_records_service'), 'knowledge_records', ['service'], unique=False)
    op.create_index(op.f('ix_knowledge_records_tenant_id'), 'knowledge_records', ['tenant_id'], unique=False)
    op.create_table('kubernetes_events',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('involved_object', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kubernetes_events_event_type'), 'kubernetes_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_kubernetes_events_reason'), 'kubernetes_events', ['reason'], unique=False)
    op.create_index(op.f('ix_kubernetes_events_timestamp'), 'kubernetes_events', ['timestamp'], unique=False)
    op.create_table('logs',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('span_id', sa.String(length=255), nullable=True),
    sa.Column('logger', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_event_id'), 'logs', ['event_id'], unique=True)
    op.create_index(op.f('ix_logs_service'), 'logs', ['service'], unique=False)
    op.create_index(op.f('ix_logs_severity'), 'logs', ['severity'], unique=False)
    op.create_index(op.f('ix_logs_timestamp'), 'logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_logs_trace_id'), 'logs', ['trace_id'], unique=False)
    op.create_table('metrics',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('cluster', sa.String(length=255), nullable=True),
    sa.Column('environment', sa.String(length=255), nullable=True),
    sa.Column('namespace', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_cluster'), 'metrics', ['cluster'], unique=False)
    op.create_index(op.f('ix_metrics_environment'), 'metrics', ['environment'], unique=False)
    op.create_index(op.f('ix_metrics_event_id'), 'metrics', ['event_id'], unique=True)
    op.create_index(op.f('ix_metrics_metric_name'), 'metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_metrics_namespace'), 'metrics', ['namespace'], unique=False)
    op.create_index(op.f('ix_metrics_service'), 'metrics', ['service'], unique=False)
    op.create_index(op.f('ix_metrics_timestamp'), 'metrics', ['timestamp'], unique=False)
    op.create_table('recoveries',
    sa.Column('recovery_id', sa.String(length=255), nullable=False),
    sa.Column('verification_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('recovery_status', sa.String(length=100), nullable=False),
    sa.Column('strategy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recoveries_recovery_id'), 'recoveries', ['recovery_id'], unique=True)
    op.create_index(op.f('ix_recoveries_tenant_id'), 'recoveries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_recoveries_verification_id'), 'recoveries', ['verification_id'], unique=False)
    op.create_table('remediations',
    sa.Column('remediation_id', sa.String(length=255), nullable=False),
    sa.Column('risk_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediations_remediation_id'), 'remediations', ['remediation_id'], unique=True)
    op.create_index(op.f('ix_remediations_risk_id'), 'remediations', ['risk_id'], unique=False)
    op.create_index(op.f('ix_remediations_service'), 'remediations', ['service'], unique=False)
    op.create_index(op.f('ix_remediations_tenant_id'), 'remediations', ['tenant_id'], unique=False)
    op.create_table('risks',
    sa.Column('risk_id', sa.String(length=255), nullable=False),
    sa.Column('rootcause_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('blast_radius', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risk_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risks_priority'), 'risks', ['priority'], unique=False)
    op.create_index(op.f('ix_risks_risk_id'), 'risks', ['risk_id'], unique=True)
    op.create_index(op.f('ix_risks_rootcause_id'), 'risks', ['rootcause_id'], unique=False)
    op.create_index(op.f('ix_risks_service'), 'risks', ['service'], unique=False)
    op.create_index(op.f('ix_risks_tenant_id'), 'risks', ['tenant_id'], unique=False)
    op.create_table('root_causes',
    sa.Column('rootcause_id', sa.String(length=255), nullable=False),
    sa.Column('investigation_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('root_cause', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('causal_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_root_causes_investigation_id'), 'root_causes', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_root_causes_rootcause_id'), 'root_causes', ['rootcause_id'], unique=True)
    op.create_index(op.f('ix_root_causes_tenant_id'), 'root_causes', ['tenant_id'], unique=False)
    op.create_table('traces',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trace_id', sa.String(length=255), nullable=False),
    sa.Column('span_id', sa.String(length=255), nullable=False),
    sa.Column('parent_span_id', sa.String(length=255), nullable=True),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('operation', sa.String(length=255), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traces_service'), 'traces', ['service'], unique=False)
    op.create_index(op.f('ix_traces_timestamp'), 'traces', ['timestamp'], unique=False)
    op.create_index(op.f('ix_traces_trace_id'), 'traces', ['trace_id'], unique=False)
    op.create_table('verifications',
    sa.Column('verification_id', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('health_status', sa.String(length=100), nullable=False),
    sa.Column('verification_result', sa.String(length=100), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_execution_id'), 'verifications', ['execution_id'], unique=False)
    op.create_index(op.f('ix_verifications_tenant_id'), 'verifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_verifications_verification_id'), 'verifications', ['verification_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verifications_verification_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_tenant_id'), table_name='verifications')
    op.drop_index(op.f('ix_verifications_execution_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_traces_trace_id'), table_name='traces')
    op.drop_index(op.f('ix_traces_timestamp'), table_name='traces')
    op.drop_index(op.f('ix_traces_service'), table_name='traces')
    op.drop_table('traces')
    op.drop_index(op.f('ix_root_causes_tenant_id'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_rootcause_id'), table_name='root_causes')
    op.drop_index(op.f('ix_root_causes_investigation_id'), table_name='root_causes')
    op.drop_table('root_causes')
    op.drop_index(op.f('ix_risks_tenant_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_service'), table_name='risks')
    op.drop_index(op.f('ix_risks_rootcause_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_risk_id'), table_name='risks')
    op.drop_index(op.f('ix_risks_priority'), table_name='risks')
    op.drop_table('risks')
    op.drop_index(op.f('ix_remediations_tenant_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_service'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_risk_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_remediation_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_recoveries_verification_id'), table_name='recoveries')
    op.drop_index(op.f('ix_recoveries_tenant_id'), table_name='recoveries')
    op.drop_index(op.f('ix_recoveries_recovery_id'), table_name='recoveries')
    op.drop_table('recoveries')
    op.drop_index(op.f('ix_metrics_timestamp'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_service'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_namespace'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_metric_name'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_event_id'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_environment'), table_name='metrics')
    op.drop_index(op.f('ix_metrics_cluster'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_logs_trace_id'), table_name='logs')
    op.drop_index(op.f('ix_logs_timestamp'), table_name='logs')
    op.drop_index(op.f('ix_logs_severity'), table_name='logs')
    op.drop_index(op.f('ix_logs_service'), table_name='logs')
    op.drop_index(op.f('ix_logs_event_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_index(op.f('ix_kubernetes_events_timestamp'), table_name='kubernetes_events')
    op.drop_index(op.f('ix_kubernetes_events_reason'), table_name='kubernetes_events')
    op.drop_index(op.f('ix_kubernetes_events_event_type'), table_name='kubernetes_events')
    op.drop_table('kubernetes_events')
    op.drop_index(op.f('ix_knowledge_records_tenant_id'), table_name='knowledge_records')
    op.drop_index(op.f('ix_knowledge_records_service'), table_name='knowledge_records')
    op.drop_index(op.f('ix_knowledge_records_knowledge_id'), table_name='knowledge_records')
    op.drop_table('knowledge_records')
    op.drop_index(op.f('ix_investigations_tenant_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_investigation_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_incident_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_service'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_incident_priority'), table_name='incidents')
    op.drop_index('idx_incident_service_priority', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_incident_states_tenant_id'), table_name='incident_states')
    op.drop_index(op.f('ix_incident_states_service'), table_name='incident_states')
    op.drop_index(op.f('ix_incident_states_incident_id'), table_name='incident_states')
    op.drop_index(op.f('ix_incident_states_current_state'), table_name='incident_states')
    op.drop_table('incident_states')
    op.drop_index(op.f('ix_executive_reports_tenant_id'), table_name='executive_reports')
    op.drop_index(op.f('ix_executive_reports_service'), table_name='executive_reports')
    op.drop_index(op.f('ix_executive_reports_report_id'), table_name='executive_reports')
    op.drop_table('executive_reports')
    op.drop_index(op.f('ix_executions_tenant_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_execution_id'), table_name='executions')
    op.drop_index(op.f('ix_executions_approval_id'), table_name='executions')
    op.drop_table('executions')
    op.drop_index(op.f('ix_execution_audits_verification_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_tenant_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_recovery_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_execution_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_audit_id'), table_name='execution_audits')
    op.drop_index(op.f('ix_execution_audits_approval_id'), table_name='execution_audits')
    op.drop_table('execution_audits')
    op.drop_index(op.f('ix_escalations_tenant_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_recovery_id'), table_name='escalations')
    op.drop_index(op.f('ix_escalations_escalation_id'), table_name='escalations')
    op.drop_table('escalations')
    op.drop_index(op.f('ix_deployments_timestamp'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_namespace'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_deployment_name'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_service'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_approval_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###
