"""add platform topics

Revision ID: e0a25474fd2c
Revises: 3220d9a7f2ac
Create Date: 2026-06-02 08:07:43.799032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0a25474fd2c'
down_revision: Union[str, Sequence[str], None] = '3220d9a7f2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregated_events',
    sa.Column('aggregation_key', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('created_at_event', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_events_aggregation_key'), 'aggregated_events', ['aggregation_key'], unique=False)
    op.create_index(op.f('ix_aggregated_events_category'), 'aggregated_events', ['category'], unique=False)
    op.create_index(op.f('ix_aggregated_events_created_at_event'), 'aggregated_events', ['created_at_event'], unique=False)
    op.create_index(op.f('ix_aggregated_events_severity'), 'aggregated_events', ['severity'], unique=False)
    op.create_index(op.f('ix_aggregated_events_tenant_id'), 'aggregated_events', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.String(length=255), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=5000), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('created_at_event', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alerts_created_at_event'), 'alerts', ['created_at_event'], unique=False)
    op.create_index(op.f('ix_alerts_service'), 'alerts', ['service'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('dead_letter_records',
    sa.Column('dlq_id', sa.String(length=255), nullable=False),
    sa.Column('source_topic', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.String(length=5000), nullable=False),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dead_letter_records_dlq_id'), 'dead_letter_records', ['dlq_id'], unique=True)
    op.create_index(op.f('ix_dead_letter_records_failed_at'), 'dead_letter_records', ['failed_at'], unique=False)
    op.create_index(op.f('ix_dead_letter_records_source_topic'), 'dead_letter_records', ['source_topic'], unique=False)
    op.create_table('processed_telemetry',
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('service', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=False),
    sa.Column('raw_event', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at_event', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_telemetry_category'), 'processed_telemetry', ['category'], unique=False)
    op.create_index(op.f('ix_processed_telemetry_created_at_event'), 'processed_telemetry', ['created_at_event'], unique=False)
    op.create_index(op.f('ix_processed_telemetry_event_id'), 'processed_telemetry', ['event_id'], unique=True)
    op.create_index(op.f('ix_processed_telemetry_event_type'), 'processed_telemetry', ['event_type'], unique=False)
    op.create_index(op.f('ix_processed_telemetry_priority'), 'processed_telemetry', ['priority'], unique=False)
    op.create_index(op.f('ix_processed_telemetry_service'), 'processed_telemetry', ['service'], unique=False)
    op.create_index(op.f('ix_processed_telemetry_severity'), 'processed_telemetry', ['severity'], unique=False)
    op.create_index(op.f('ix_processed_telemetry_tenant_id'), 'processed_telemetry', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_telemetry_tenant_id'), table_name='processed_telemetry')
    op.drop_index(op.f('ix_processed_telemetry_severity'), table_name='processed_telemetry')
    op.drop_index(op.f('ix_processed_telemetry_service'), table_name='processed_telemetry')
    op.drop_index(op.f('ix_processed_telemetry_priority'), table_name='processed_telemetry')
    op.drop_index(op.f('ix_processed_telemetry_event_type'), table_name='processed_telemetry')
    op.drop_index(op.f('ix_processed_telemetry_event_id'), table_name='processed_telemetry')
    op.drop_index(op.f('ix_processed_telemetry_created_at_event'), table_name='processed_telemetry')
    op.drop_index(op.f('ix_processed_telemetry_category'), table_name='processed_telemetry')
    op.drop_table('processed_telemetry')
    op.drop_index(op.f('ix_dead_letter_records_source_topic'), table_name='dead_letter_records')
    op.drop_index(op.f('ix_dead_letter_records_failed_at'), table_name='dead_letter_records')
    op.drop_index(op.f('ix_dead_letter_records_dlq_id'), table_name='dead_letter_records')
    op.drop_table('dead_letter_records')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_service'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at_event'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_aggregated_events_tenant_id'), table_name='aggregated_events')
    op.drop_index(op.f('ix_aggregated_events_severity'), table_name='aggregated_events')
    op.drop_index(op.f('ix_aggregated_events_created_at_event'), table_name='aggregated_events')
    op.drop_index(op.f('ix_aggregated_events_category'), table_name='aggregated_events')
    op.drop_index(op.f('ix_aggregated_events_aggregation_key'), table_name='aggregated_events')
    op.drop_table('aggregated_events')
    # ### end Alembic commands ###
